// Starter catalogue - copied from the original frontend file src/data/products.ts.
// `id` and `categoryLabel` are intentionally absent: MongoDB assigns ids and the
// server derives categoryLabel from `category` (see utils/serialize.js).

export const SEED_PRODUCTS = [
  {
    name: 'Royal Black & Gold Tuxedo Suit',
    category: 'suti',
    price: 380000,
    originalPrice: 450000,
    description:
      'Suti ya daraja la kwanza ya velvet na vitufe vya dhahabu, imeshonwa kwa ustadi wa hali ya juu kwa ajili ya harusi, sherehe na mikutano mikuu ya kibiashara.',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['48 / S', '50 / M', '52 / L', '54 / XL', '56 / XXL'],
    colors: [
      { name: 'Nyeusi ya Kifahari', hex: '#0B0D12' },
      { name: 'Navy Blue & Gold', hex: '#0F1D38' },
      { name: 'Emerald Green', hex: '#0D3324' },
    ],
    inStock: true,
    rating: 4.9,
    reviewsCount: 42,
    badge: 'Maarufu Zaidi',
    featured: true,
  },
  {
    name: 'Classic Double-Breasted Slim Suit',
    category: 'suti',
    price: 320000,
    originalPrice: 380000,
    description:
      'Suti ya kisasa ya vishikizo sita (Double-Breasted), kitambaa chepesi cha pamba ya kiitaliano kinachopumua na kutoa mwonekano wa heshima na nguvu.',
    image: 'https://images.unsplash.com/photo-1598808503746-f34c53b9323e?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['48 / S', '50 / M', '52 / L', '54 / XL'],
    colors: [
      { name: 'Charcoal Grey', hex: '#2A2C30' },
      { name: 'Midnight Black', hex: '#111215' },
      { name: 'Camel Tan', hex: '#8C6843' },
    ],
    inStock: true,
    rating: 4.8,
    reviewsCount: 31,
    badge: 'Toleo Jipya',
    featured: true,
  },
  {
    name: 'Hilaly Presidential Kaunda Suit',
    category: 'wanaume',
    price: 185000,
    originalPrice: 220000,
    description:
      'Kaunda suit ya kisasa yenye kola ya kipekee na mikono mifupi, inayovaliwa na viongozi na wafanyabiashara mashuhuri kote Afrika Mashariki.',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Onyx Black', hex: '#15171B' },
      { name: 'Desert Khaki', hex: '#87765A' },
      { name: 'Olive Green', hex: '#374233' },
    ],
    inStock: true,
    rating: 5,
    reviewsCount: 56,
    badge: 'Chaguo la Viongozi',
    featured: true,
  },
  {
    name: 'Luxury Silk Satin Evening Gown',
    category: 'wanawake',
    price: 260000,
    originalPrice: 310000,
    description:
      'Gauni refu la kifahari la hariri (silk satin) lenye mpasuo maridadi na mkanda wa nakshi za dhahabu, linafaa kwa hafla za kifahari za jioni na red carpet.',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['38 / S', '40 / M', '42 / L', '44 / XL'],
    colors: [
      { name: 'Gold Champagne', hex: '#D4AF37' },
      { name: 'Royal Emerald', hex: '#0B3B2B' },
      { name: 'Ruby Wine', hex: '#4A0E17' },
    ],
    inStock: true,
    rating: 4.9,
    reviewsCount: 29,
    badge: 'Mkusanyiko Maalum',
    featured: true,
  },
  {
    name: 'Dubai Hand-Embroidered Abaya',
    category: 'wanawake',
    price: 210000,
    originalPrice: 250000,
    description:
      'Abaya ya kitambaa cha Nada chenye nakshi za shanga za dhahabu zilizoshonwa kwa mkono, inakuja pamoja na mtandio wa hariri.',
    image: 'https://images.unsplash.com/photo-1583846783214-7229a91b20ed?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['52 (M)', '54 (L)', '56 (XL)', '58 (XXL)'],
    colors: [
      { name: 'Deep Black & Gold', hex: '#0A0A0C' },
      { name: 'Mocha Brown', hex: '#3E2F26' },
      { name: 'Soft Sage', hex: '#4C584E' },
    ],
    inStock: true,
    rating: 4.9,
    reviewsCount: 38,
    badge: 'Imependwa',
    featured: false,
  },
  {
    name: 'Handcrafted Italian Leather Oxford Shoes',
    category: 'viatu',
    price: 195000,
    originalPrice: 240000,
    description:
      'Viatu vya asili vya ngozi ya ng’ombe vilivyong’arishwa kwa mikono, soli imara ya kudumu miaka mingi na muundo unalinda mguu vizuri.',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['40', '41', '42', '43', '44', '45'],
    colors: [
      { name: 'Burnished Tan Brown', hex: '#633B1E' },
      { name: 'Glossy Black', hex: '#141416' },
    ],
    inStock: true,
    rating: 4.8,
    reviewsCount: 47,
    badge: 'Ngozi Halisi',
    featured: true,
  },
  {
    name: 'Luxury Suede Tassel Loafers',
    category: 'viatu',
    price: 165000,
    originalPrice: 195000,
    description:
      'Viatu vya mtindo wa velvet suede vyenye kishada cha pindo (tassel), vyepesi sana na vinapendeza mno ukiwa na suruali za pamba au jeans ya heshima.',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['40', '41', '42', '43', '44'],
    colors: [
      { name: 'Midnight Navy', hex: '#142038' },
      { name: 'Rich Tobacco', hex: '#583D28' },
    ],
    inStock: true,
    rating: 4.7,
    reviewsCount: 22,
    badge: 'Mtindo Mpya',
    featured: false,
  },
  {
    name: 'Hilaly Gold Chronograph Luxury Watch',
    category: 'accessories',
    price: 240000,
    originalPrice: 290000,
    description:
      'Saa ya chuma cha pua kilichopakwa dhahabu ya karati 18 (18K Gold Plated), haipitishi maji hadi mita 50, inakuja na kasha rasmi la mbao ya Hilaly.',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['Standard 42mm'],
    colors: [
      { name: 'Pure Gold & Black Dial', hex: '#D4AF37' },
      { name: 'Rose Gold & Blue', hex: '#B76E79' },
    ],
    inStock: true,
    rating: 5,
    reviewsCount: 64,
    badge: 'Toleo Maalum',
    featured: true,
  },
  {
    name: 'Designer Reversible Leather Belt & Cufflinks',
    category: 'accessories',
    price: 85000,
    originalPrice: 110000,
    description:
      'Seti kamili ya mkanda wa ngozi halisi unageuka pande mbili (Nyeusi & Kahawia) pamoja na vifungo vya mikono ya shati (cufflinks) vya dhahabu.',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80',
    images: [],
    sizes: ['32 - 36', '38 - 42', '44 - 48'],
    colors: [
      { name: 'Gold Buckle / Dual Leather', hex: '#C5A059' },
    ],
    inStock: true,
    rating: 4.8,
    reviewsCount: 19,
    badge: 'Seti Kamili',
    featured: false,
  },
];
